baseURL = 'https://trieste-cmsp.github.io/seminars/'
languageCode = 'en-us'
title = 'Trieste CMSP Seminars'

# [module]
#   [[module.imports]]
#     path = "github.com/hugo-sid/hugo-blog-awesome"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[caches]
  [caches.images]
    dir = ':cacheDir/images'
